### ISSUE TITLE
System tray Icon no more showing notification

### ISSUE THREAD

**Issue by ajvurz** [timche/gmail-desktop#327]
**OS**
Operating System: Linux Mint 20.3
Kernel: Linux 5.13.0-27-generic
Architecture: x86-64

**Gmail Desktop Version**
gmail-desktop-2.25.3-linux
Installed from .deb package.

**Describe the bug**
System tray Icon no more showing notification. I have now continuously a white icon. Installed the application more than one year ago and one month ago I noticed that I have no more notification for new mails by the icon becaming colored. Some rsources missing probably, I cannot see why.
The pop-up notification is working fine.

**Comment by BluGum** [comment]
I'm having a similar issue on MacOS. In the past few weeks the Gmail Desktop dock icon has stopped showing a red notification indicator when new mail arrives. I've tried reinstalling the app and resetting my notification settings but neither has worked. 

**Device & OS**
Device: MacBook Pro 16-inch (2019)
Operating System: MacOS Monterey 12.2.1

**Gmail Desktop Version**
Version 2.25.3 (2.25.3)

**Comment by timche** [comment]
Thanks for reporting this issue. It's probably due to changes on behalf of Gmail and the selector to read the unread inbox isn't working anymore. I suggest you both @ajvurz and @BluGum to use the [latest v3-alpha](https://github.com/timche/gmail-desktop/releases) instead, because I won't be maintaining v2 anymore as v3 is planned to be released soon.
