### ISSUE TITLE
Add context menu

### ISSUE THREAD

**Issue by timche** [timche/gmail-desktop#74]
Right-clicking on elements and input fields doesn't do anything yet. It should instead show a context menu to do various things like `Copy link`, etc. (TBD) using [electron-context-menu](https://github.com/sindresorhus/electron-context-menu).

**Comment by cipriancraciun** [comment]
At the moment copy-link is essential, especially for those that use multiple browsers / browser profiles.

For example say I receive an email with an alert from a cloud provider, with a link that contains more details, or an action to be taken.  If I use a different browser profile (or even browser instance) to manage my AWS account, if I click that link it opens in my default browser, which due to how the web-application is implemented redirects me to a login page, and my original link is (at best) obscured or (at worst, which is usually) lost.

---

Fortunately in my case I have a custom `xdg-open` script that allows me to intercept the external links, however for the normal user getting to the original link could be an ordeal.

(In fact having this custom `xdg-open` script is another reason what prompted me to switch from the browser to the Electron based application, because I can open links in different browsers / profiles based on their domain.)

**Comment by markypython** [comment]
Added in [v2.8.0](https://github.com/timche/gmail-desktop/releases/tag/v2.8.0)
