### ISSUE TITLE
User custom styles

### ISSUE THREAD

**Issue by timche** [timche/gmail-desktop#77]
Inspired by: https://github.com/sindresorhus/caprine#custom-styles

**Comment by cipriancraciun** [comment]
Indeed having custom styles would be helpful for the advanced GMail user.

I would envisage that even a simple `Custom mode` (similar to `Minimal mode`) would be enough, that would allow one to enable / disable the custom CSS in a file.

---

Some time ago, by using the Stylish Firefox addon (https://userstyles.org/help/stylish) I wrote a few custom CSS styles to make the GMail inbox and thread view less cluttered and to allow me to focus on the actual emails.

(Unfortunately I had to drop it after a few years, because GMail changed their CSS labels and structure, perhaps due to a new build, given that they use something similar to GWT.)

There are however quite a few custom styles for GMail: https://userstyles.org/styles/browse?search_terms=mail.google.com

**Comment by markypython** [comment]
@cipriancraciun I don't think that we would need a setting, but rather we would just check for the existence of a custom css file.  Then, we can just have a menu link that will open that file in the default application.

@timche Thoughts?

**Comment by timche** [comment]
Right, like kinda like described here: https://github.com/sindresorhus/caprine#custom-styles

**Comment by cipriancraciun** [comment]
@markypython If the user doesn't have the option to enable / disable the custom user styles, then if GMail changes something in its HTML structure (and usage of CSS classes), it would be quite difficult to use it.

Moreover, the same functionality is required if the user has multiple (perhaps delegated) GMail accounts that use different themes, because GMail has different (but not quite a completely distinct set of) CSS classes for different themes.  Therefore when the user is in such a situation, it would be helpful to temporarily disable the custom style.

**Comment by markypython** [comment]
> then if GMail changes something in its HTML structure (and usage of CSS classes)

If this were to happen, I would expect that I would either have to update my custom stylesheet or I would have to simply remove the old styles.  I don't think a setting to turn off the custom styles would be necessary.

> Moreover, the same functionality is required if the user has multiple (perhaps delegated) GMail accounts that use different themes

I'm not familiar with Gmail account delegation.  Does the user have the ability to change the theme for the delegated account?  If so, I would expect that most users would have the same theme for all their accounts.

**Comment by cipriancraciun** [comment]
> @markypython I'm not familiar with Gmail account delegation. Does the user have the ability to change the theme for the delegated account? If so, I would expect that most users would have the same theme for all their accounts.

No, the user receiving the delegation can't change the delegated account theme.  However he does **get the delegated account theme**.  (I.e. his own account uses his theme, the delegated account uses that particular account's theme.)  (This is based on my concrete experience with delegated accounts.)

**Comment by markypython** [comment]
Thanks for the info.  I'll have to noodle on this for a bit.

**Comment by cipriancraciun** [comment]
> > then if GMail changes something in its HTML structure (and usage of CSS classes)
> 
> @markypython If this were to happen, I would expect that I would either have to update my custom stylesheet or I would have to simply remove the old styles. I don't think a setting to turn off the custom styles would be necessary.

I wont press this further than this:  please believe me that I speak out of concrete experience with using custom styles with GMail.  There were countless times when I had to temporarily disable the custom style for various reasons, like for example:

* using a delegated account that uses a different theme (as discussed above);
* receiving an email that contains HTML that behaves poorly with the custom style;  (I used to force styling on the actual email `div` and children, so that I can more easily read them, especially given that many of my corespondents used HTML, as opposed to plain text emails, with strange fonts, and even rainbow colors...  especially more-so in case of newsletters and various system generated emails;)
* accessing a new feature of GMail that I usually didn't and for which my custom style wasn't ready for;

**Comment by timche** [comment]
I'd like to have the following UX:
1. `Settings` -> `Custom Styles` -> `Enabled`
  - Will enable and inject the custom styles
2. `Settings` -> `Custom Styles` -> `Edit CSS File`
  - Will open the CSS file in the default editor

**Comment by cipriancraciun** [comment]
I've just played with `custom.css` a little bit, and from what I gather it is not injected into "non-main" windows.

For example if one wants to compose an email into a new window (i.e. hold Shift and click the compose button), then that window doesn't have the `custom.css` injected.
